package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.FloorCommodity;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface FloorCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Delete({
        "delete from floor_commodity",
        "where COMMODITY_ID = #{commodityId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("commodityId") Integer commodityId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Insert({
        "insert into floor_commodity (COMMODITY_ID, FLOOR_ID, ",
        "SORT_ORDER)",
        "values (#{commodityId,jdbcType=INTEGER}, #{floorId,jdbcType=INTEGER}, ",
        "#{sortOrder,jdbcType=INTEGER})"
    })
    int insert(FloorCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Select({
        "select",
        "COMMODITY_ID, FLOOR_ID, SORT_ORDER",
        "from floor_commodity",
        "where COMMODITY_ID = #{commodityId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="COMMODITY_ID", property="commodityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    FloorCommodity selectByPrimaryKey(@Param("commodityId") Integer commodityId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Select({
        "select",
        "COMMODITY_ID, FLOOR_ID, SORT_ORDER",
        "from floor_commodity"
    })
    @Results({
        @Result(column="COMMODITY_ID", property="commodityId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorCommodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Update({
        "update floor_commodity",
        "set SORT_ORDER = #{sortOrder,jdbcType=INTEGER}",
        "where COMMODITY_ID = #{commodityId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FloorCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_commodity
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    @Select({
            "select",
            "COMMODITY_ID, FLOOR_ID, SORT_ORDER",
            "from floor_commodity",
            "where FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="COMMODITY_ID", property="commodityId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorCommodity> selectByFloorId(Integer floorId);
}