package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.FloorCategory;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface FloorCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Delete({
        "delete from floor_category",
        "where CATEGORY_ID = #{categoryId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("categoryId") Integer categoryId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Insert({
        "insert into floor_category (CATEGORY_ID, FLOOR_ID, ",
        "SORT_ORDER)",
        "values (#{categoryId,jdbcType=INTEGER}, #{floorId,jdbcType=INTEGER}, ",
        "#{sortOrder,jdbcType=INTEGER})"
    })
    int insert(FloorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Select({
        "select",
        "CATEGORY_ID, FLOOR_ID, SORT_ORDER",
        "from floor_category",
        "where CATEGORY_ID = #{categoryId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    FloorCategory selectByPrimaryKey(@Param("categoryId") Integer categoryId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Select({
        "select",
        "CATEGORY_ID, FLOOR_ID, SORT_ORDER",
        "from floor_category"
    })
    @Results({
        @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Update({
        "update floor_category",
        "set SORT_ORDER = #{sortOrder,jdbcType=INTEGER}",
        "where CATEGORY_ID = #{categoryId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FloorCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_category
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    @Select({
            "select",
            "CATEGORY_ID, FLOOR_ID, SORT_ORDER",
            "from floor_category",
            "where FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorCategory> selectByFloorId(Integer floorId);
}