# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crystal_ball?useUnicode=true&autoReconnect=true
    username: root
    password: Yunxin1234
  session:
     store-type: none
  jpa:
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: com.yunxin.core.orm.ImprovedPhysicalNamingStrategy
      show-sql: true
      open-in-view: false
      properties:
          hibernate.format_sql: true
          hibernate.search.default.indexBase: /opt/www/cb/admin/index
  resources:
      #资源缓存时间，单位秒
      cache-period: 604800
      chain:
          #开启gzip压缩
          gzipped: true
          #启用缓存
          cache: true
  mvc:
      view:
          # 页面默认前缀目录
          prefix: /WEB-INF/jsp/
          # 响应页面默认后缀
          suffix: .jsp
#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball
  domain-1: http://test.resource.999shuijingqiu.com/

#融云IM
rongcloud:
  appKey: z3v5yqkbz1jp0
  appSecret: AUUwTO6vXg7y7P

#APP自定义配置
application:
  default:
    avatarUrl: http://test.resource.999shuijingqiu.com/avatar.png
  uploadPath: /opt/www
  searchBaseUrl: http://localhost:8168/search/