# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://172.18.59.156:3306/crystal_ball?useUnicode=true&autoReconnect=true
    username: root
    password: Yunxin@2018!#%
  session:
     store-type: none
  redis:
     database: 0
     host: 172.18.59.156
     port: 6321
     password: redis_p@ssw0rd
     timeout: 0
     pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
  jpa:
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: com.yunxin.core.orm.ImprovedPhysicalNamingStrategy
      show-sql: false
      open-in-view: false
      properties:
          hibernate.format_sql: false
          hibernate.search.default.indexBase: /data/webapps/admin/temp/index
  resources:
      #资源缓存时间，单位秒
      cache-period: 604800
      chain:
          #开启gzip压缩
          gzipped: true
          #启用缓存
          cache: true
  mvc:
      view:
          # 页面默认前缀目录
          prefix: /WEB-INF/jsp/
          # 响应页面默认后缀
          suffix: .jsp

#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball-prod
  domain-1: http://resource.999shuijingqiu.com/

#融云IM
rongcloud:
  appKey: vnroth0kv8sxo
  appSecret: xR4RmfFyJhA

#APP自定义配置
application:
  default:
    avatarUrl: http://resource.999shuijingqiu.com/avatar.png
  uploadPath: /data/webapps/admin/temp/images
  searchBaseUrl: http://localhost:8168/search/