package com.yunxin.cb.sns.entity;

// Generated 2010-4-1 12:26:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicCollectionId generated by hbm2java
 */
@Embeddable
public class CustomerFriendId implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int customerId;
    private int friendId;

    public CustomerFriendId() {
    }

    public CustomerFriendId(int customerId, int friendId) {
        this.customerId = customerId;
        this.friendId = friendId;
    }

    @Column(nullable = false)
    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int userId) {
        this.customerId = userId;
    }

    @Column(nullable = false)
    public int getFriendId() {
        return this.friendId;
    }

    public void setFriendId(int musicId) {
        this.friendId = musicId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CustomerFriendId that = (CustomerFriendId) o;

        if (customerId != that.customerId) return false;
        return friendId == that.friendId;

    }

    @Override
    public int hashCode() {
        int result = customerId;
        result = 31 * result + friendId;
        return result;
    }
}
