version: "3"
services:
  cb-admin:
    image: 192.168.0.22/crystal-ball/cb-admin:car-mall
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
    command: ["--spring.profiles.active=dev"]
    networks:
      - crystal-ball-cloud
    ports:
      - "8184:8080"
    logging:
      options:
        max-size: "10m"

networks:
  crystal-ball-cloud:
    external:
      name: "crystal-ball-cloud"