# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/crystal_ball?useUnicode=true&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
     store-type: none
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yunxin.cb.entity
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball
  domain-1: http://test.resource.999shuijingqiu.com/

#融云IM
rongcloud:
  appKey: z3v5yqkbz1jp0
  appSecret: AUUwTO6vXg7y7P

#APP自定义配置
application:
  default:
    avatarUrl: http://pb9sg55i7.bkt.clouddn.com/avatar.png
  searchBaseUrl: http://localhost:8168/search/
