# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crystal_ball?useUnicode=true&autoReconnect=true
    username: root
    password: Yunxin@2018!#%
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  session:
     store-type: none
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yunxin.cb.entity
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball-prod
  domain-1: http://resource.999shuijingqiu.com/

