package com.yunxin.cb.mall.entity;

import java.util.Date;

/**
 * 运营分类
 */
public class Category implements java.io.Serializable{
    private static final long serialVersionUID = 2018268694837623318L;
    /**
     *
     */
    private Integer categoryId;

    /**
     * 分类关键字
     */
    private String categoryKey;

    /**
     * 分类名称
     */
    private String categoryName;

    /**
     * 分类编号
     */
    private String categoryNo;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 分类描述
     */
    private String description;

    /**
     * 是否启用
     */
    private Boolean enabled;

    /**
     * 图标路径
     */
    private String iconPath;

    /**
     * 分类级别作为限制层级用途
     */
    private Integer level;

    /**
     * 是否推荐
     */
    private Boolean recommend;

    /**
     *
     */
    private String remark;

    /**
     * SEO描述
     */
    private String seoDescription;

    /**
     * SEO关键字
     */
    private String seoKey;

    /**
     *
     */
    private String seoTitle;

    /**
     * 排序号
     */
    private Integer sortOrder;

    /**
     *
     */
    private Integer parentCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CATEGORY_ID
     *
     * @return the value of category.CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CATEGORY_ID
     *
     * @param categoryId the value for category.CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CATEGORY_KEY
     *
     * @return the value of category.CATEGORY_KEY
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getCategoryKey() {
        return categoryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CATEGORY_KEY
     *
     * @param categoryKey the value for category.CATEGORY_KEY
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setCategoryKey(String categoryKey) {
        this.categoryKey = categoryKey == null ? null : categoryKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CATEGORY_NAME
     *
     * @return the value of category.CATEGORY_NAME
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CATEGORY_NAME
     *
     * @param categoryName the value for category.CATEGORY_NAME
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CATEGORY_NO
     *
     * @return the value of category.CATEGORY_NO
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CATEGORY_NO
     *
     * @param categoryNo the value for category.CATEGORY_NO
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CREATE_TIME
     *
     * @return the value of category.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CREATE_TIME
     *
     * @param createTime the value for category.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.DESCRIPTION
     *
     * @return the value of category.DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.DESCRIPTION
     *
     * @param description the value for category.DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.ENABLED
     *
     * @return the value of category.ENABLED
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.ENABLED
     *
     * @param enabled the value for category.ENABLED
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.ICON_PATH
     *
     * @return the value of category.ICON_PATH
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.ICON_PATH
     *
     * @param iconPath the value for category.ICON_PATH
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath == null ? null : iconPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.LEVEL
     *
     * @return the value of category.LEVEL
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.LEVEL
     *
     * @param level the value for category.LEVEL
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.RECOMMEND
     *
     * @return the value of category.RECOMMEND
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.RECOMMEND
     *
     * @param recommend the value for category.RECOMMEND
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.REMARK
     *
     * @return the value of category.REMARK
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.REMARK
     *
     * @param remark the value for category.REMARK
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.SEO_DESCRIPTION
     *
     * @return the value of category.SEO_DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.SEO_DESCRIPTION
     *
     * @param seoDescription the value for category.SEO_DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription == null ? null : seoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.SEO_KEY
     *
     * @return the value of category.SEO_KEY
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getSeoKey() {
        return seoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.SEO_KEY
     *
     * @param seoKey the value for category.SEO_KEY
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setSeoKey(String seoKey) {
        this.seoKey = seoKey == null ? null : seoKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.SEO_TITLE
     *
     * @return the value of category.SEO_TITLE
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.SEO_TITLE
     *
     * @param seoTitle the value for category.SEO_TITLE
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle == null ? null : seoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.SORT_ORDER
     *
     * @return the value of category.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.SORT_ORDER
     *
     * @param sortOrder the value for category.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.PARENT_CATEGORY_ID
     *
     * @return the value of category.PARENT_CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public Integer getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.PARENT_CATEGORY_ID
     *
     * @param parentCategoryId the value for category.PARENT_CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 10:47:25 CST 2018
     */
    public void setParentCategoryId(Integer parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }
}