/**
 *
 */
package com.yunxin.cb.mall.entity;



import java.util.Date;


/**
 * @author z001075  商品
 */

public class Commodity implements java.io.Serializable {

    /***/
    private static final long serialVersionUID = -3113613325145218113L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.AUDIT_REMARK
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String auditRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.BARTER
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean barter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CITY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_CODE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String commodityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_PYNAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String commodityPyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer commodityState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COMMODITY_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String commodityTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CONTENT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.COST_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Double costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.DEFAULT_PIC_PATH
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String defaultPicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.DELIVERY_TYPE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer deliveryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.FORBID_AIR_CARGO
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean forbidAirCargo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.GIVEAWAY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean giveaway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.MARKET_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Double marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.POPULAR
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean popular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.PRE_SELL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean preSell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.PROVINCE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.PUBLISH_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer publishState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.RECOMMEND
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SALE_NUM
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer saleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SELL_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Double sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SEO_DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String seoDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SEO_KEY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String seoKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SEO_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String seoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SHORT_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SPECIAL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Boolean special;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.UNIT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.VOLUME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Double volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.WEIGHT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.CATALOG_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SECTION_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.SELLER_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private Integer sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.PACKING_LIST
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    private String packingList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_ID
     *
     * @return the value of commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_ID
     *
     * @param commodityId the value for commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.AUDIT_REMARK
     *
     * @return the value of commodity.AUDIT_REMARK
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.AUDIT_REMARK
     *
     * @param auditRemark the value for commodity.AUDIT_REMARK
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark == null ? null : auditRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.BARTER
     *
     * @return the value of commodity.BARTER
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getBarter() {
        return barter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.BARTER
     *
     * @param barter the value for commodity.BARTER
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setBarter(Boolean barter) {
        this.barter = barter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CITY
     *
     * @return the value of commodity.CITY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CITY
     *
     * @param city the value for commodity.CITY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_CODE
     *
     * @return the value of commodity.COMMODITY_CODE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_CODE
     *
     * @param commodityCode the value for commodity.COMMODITY_CODE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_NAME
     *
     * @return the value of commodity.COMMODITY_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_NAME
     *
     * @param commodityName the value for commodity.COMMODITY_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_PYNAME
     *
     * @return the value of commodity.COMMODITY_PYNAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getCommodityPyname() {
        return commodityPyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_PYNAME
     *
     * @param commodityPyname the value for commodity.COMMODITY_PYNAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityPyname(String commodityPyname) {
        this.commodityPyname = commodityPyname == null ? null : commodityPyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_STATE
     *
     * @return the value of commodity.COMMODITY_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getCommodityState() {
        return commodityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_STATE
     *
     * @param commodityState the value for commodity.COMMODITY_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityState(Integer commodityState) {
        this.commodityState = commodityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COMMODITY_TITLE
     *
     * @return the value of commodity.COMMODITY_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getCommodityTitle() {
        return commodityTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COMMODITY_TITLE
     *
     * @param commodityTitle the value for commodity.COMMODITY_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCommodityTitle(String commodityTitle) {
        this.commodityTitle = commodityTitle == null ? null : commodityTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CONTENT
     *
     * @return the value of commodity.CONTENT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CONTENT
     *
     * @param content the value for commodity.CONTENT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.COST_PRICE
     *
     * @return the value of commodity.COST_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.COST_PRICE
     *
     * @param costPrice the value for commodity.COST_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CREATE_TIME
     *
     * @return the value of commodity.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CREATE_TIME
     *
     * @param createTime the value for commodity.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.DEFAULT_PIC_PATH
     *
     * @return the value of commodity.DEFAULT_PIC_PATH
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getDefaultPicPath() {
        return defaultPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.DEFAULT_PIC_PATH
     *
     * @param defaultPicPath the value for commodity.DEFAULT_PIC_PATH
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setDefaultPicPath(String defaultPicPath) {
        this.defaultPicPath = defaultPicPath == null ? null : defaultPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.DELIVERY_TYPE
     *
     * @return the value of commodity.DELIVERY_TYPE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.DELIVERY_TYPE
     *
     * @param deliveryType the value for commodity.DELIVERY_TYPE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setDeliveryType(Integer deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.DESCRIPTION
     *
     * @return the value of commodity.DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.DESCRIPTION
     *
     * @param description the value for commodity.DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.FORBID_AIR_CARGO
     *
     * @return the value of commodity.FORBID_AIR_CARGO
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getForbidAirCargo() {
        return forbidAirCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.FORBID_AIR_CARGO
     *
     * @param forbidAirCargo the value for commodity.FORBID_AIR_CARGO
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setForbidAirCargo(Boolean forbidAirCargo) {
        this.forbidAirCargo = forbidAirCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.GIVEAWAY
     *
     * @return the value of commodity.GIVEAWAY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getGiveaway() {
        return giveaway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.GIVEAWAY
     *
     * @param giveaway the value for commodity.GIVEAWAY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setGiveaway(Boolean giveaway) {
        this.giveaway = giveaway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.MARKET_PRICE
     *
     * @return the value of commodity.MARKET_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.MARKET_PRICE
     *
     * @param marketPrice the value for commodity.MARKET_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.POPULAR
     *
     * @return the value of commodity.POPULAR
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getPopular() {
        return popular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.POPULAR
     *
     * @param popular the value for commodity.POPULAR
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setPopular(Boolean popular) {
        this.popular = popular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.PRE_SELL
     *
     * @return the value of commodity.PRE_SELL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getPreSell() {
        return preSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.PRE_SELL
     *
     * @param preSell the value for commodity.PRE_SELL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setPreSell(Boolean preSell) {
        this.preSell = preSell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.PROVINCE
     *
     * @return the value of commodity.PROVINCE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.PROVINCE
     *
     * @param province the value for commodity.PROVINCE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.PUBLISH_STATE
     *
     * @return the value of commodity.PUBLISH_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getPublishState() {
        return publishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.PUBLISH_STATE
     *
     * @param publishState the value for commodity.PUBLISH_STATE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setPublishState(Integer publishState) {
        this.publishState = publishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.RECOMMEND
     *
     * @return the value of commodity.RECOMMEND
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.RECOMMEND
     *
     * @param recommend the value for commodity.RECOMMEND
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SALE_NUM
     *
     * @return the value of commodity.SALE_NUM
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SALE_NUM
     *
     * @param saleNum the value for commodity.SALE_NUM
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SELL_PRICE
     *
     * @return the value of commodity.SELL_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SELL_PRICE
     *
     * @param sellPrice the value for commodity.SELL_PRICE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SEO_DESCRIPTION
     *
     * @return the value of commodity.SEO_DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SEO_DESCRIPTION
     *
     * @param seoDescription the value for commodity.SEO_DESCRIPTION
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription == null ? null : seoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SEO_KEY
     *
     * @return the value of commodity.SEO_KEY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getSeoKey() {
        return seoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SEO_KEY
     *
     * @param seoKey the value for commodity.SEO_KEY
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSeoKey(String seoKey) {
        this.seoKey = seoKey == null ? null : seoKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SEO_TITLE
     *
     * @return the value of commodity.SEO_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SEO_TITLE
     *
     * @param seoTitle the value for commodity.SEO_TITLE
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle == null ? null : seoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SHORT_NAME
     *
     * @return the value of commodity.SHORT_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SHORT_NAME
     *
     * @param shortName the value for commodity.SHORT_NAME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SPECIAL
     *
     * @return the value of commodity.SPECIAL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Boolean getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SPECIAL
     *
     * @param special the value for commodity.SPECIAL
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSpecial(Boolean special) {
        this.special = special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.UNIT
     *
     * @return the value of commodity.UNIT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.UNIT
     *
     * @param unit the value for commodity.UNIT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.VOLUME
     *
     * @return the value of commodity.VOLUME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.VOLUME
     *
     * @param volume the value for commodity.VOLUME
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.WEIGHT
     *
     * @return the value of commodity.WEIGHT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.WEIGHT
     *
     * @param weight the value for commodity.WEIGHT
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.BRAND_ID
     *
     * @return the value of commodity.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.BRAND_ID
     *
     * @param brandId the value for commodity.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.CATALOG_ID
     *
     * @return the value of commodity.CATALOG_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.CATALOG_ID
     *
     * @param catalogId the value for commodity.CATALOG_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SECTION_ID
     *
     * @return the value of commodity.SECTION_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SECTION_ID
     *
     * @param sectionId the value for commodity.SECTION_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.SELLER_ID
     *
     * @return the value of commodity.SELLER_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public Integer getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.SELLER_ID
     *
     * @param sellerId the value for commodity.SELLER_ID
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.PACKING_LIST
     *
     * @return the value of commodity.PACKING_LIST
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public String getPackingList() {
        return packingList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.PACKING_LIST
     *
     * @param packingList the value for commodity.PACKING_LIST
     *
     * @mbg.generated Wed Jul 18 14:34:39 CST 2018
     */
    public void setPackingList(String packingList) {
        this.packingList = packingList == null ? null : packingList.trim();
    }
}
