package com.yunxin.cb.mall.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ACCOUNT_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ADDRESS
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.BIRTHDAY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CARD_NO
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CITY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CREATE_TIME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CUSTOMER_TYPE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.DISTRICT
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.EMAIL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ENABLED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.EXCHANGE_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer exchangeIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Boolean mailChecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MOBILE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.MOBILE_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Boolean mobileChecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PASSWORD
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.POST_CODE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PROVINCE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.QQ_ACCESS_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String qqAccessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.QQ_FIGURE_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String qqFigureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.QQ_NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String qqNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.QQ_OPEN_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String qqOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.REAL_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.REMARK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.SEX
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.TELEPHONE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.TOTAL_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer totalIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RANK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.EMAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Boolean emailChecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RONG_CLOUD_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String rongCloudToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.AVATAR_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer recommendCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PRAISE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer praise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.PRAISE_NUM
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    private Integer praiseNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_ID
     *
     * @return the value of customer.CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_ID
     *
     * @param customerId the value for customer.CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ACCOUNT_NAME
     *
     * @return the value of customer.ACCOUNT_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ACCOUNT_NAME
     *
     * @param accountName the value for customer.ACCOUNT_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ADDRESS
     *
     * @return the value of customer.ADDRESS
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ADDRESS
     *
     * @param address the value for customer.ADDRESS
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.NICK_NAME
     *
     * @return the value of customer.NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.NICK_NAME
     *
     * @param nickName the value for customer.NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.BIRTHDAY
     *
     * @return the value of customer.BIRTHDAY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.BIRTHDAY
     *
     * @param birthday the value for customer.BIRTHDAY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CARD_NO
     *
     * @return the value of customer.CARD_NO
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CARD_NO
     *
     * @param cardNo the value for customer.CARD_NO
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CITY
     *
     * @return the value of customer.CITY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CITY
     *
     * @param city the value for customer.CITY
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CREATE_TIME
     *
     * @return the value of customer.CREATE_TIME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CREATE_TIME
     *
     * @param createTime the value for customer.CREATE_TIME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CUSTOMER_TYPE
     *
     * @return the value of customer.CUSTOMER_TYPE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CUSTOMER_TYPE
     *
     * @param customerType the value for customer.CUSTOMER_TYPE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setCustomerType(Integer customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.DISTRICT
     *
     * @return the value of customer.DISTRICT
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.DISTRICT
     *
     * @param district the value for customer.DISTRICT
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.EMAIL
     *
     * @return the value of customer.EMAIL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.EMAIL
     *
     * @param email the value for customer.EMAIL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ENABLED
     *
     * @return the value of customer.ENABLED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ENABLED
     *
     * @param enabled the value for customer.ENABLED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.EXCHANGE_INTEGRAL
     *
     * @return the value of customer.EXCHANGE_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getExchangeIntegral() {
        return exchangeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.EXCHANGE_INTEGRAL
     *
     * @param exchangeIntegral the value for customer.EXCHANGE_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setExchangeIntegral(Integer exchangeIntegral) {
        this.exchangeIntegral = exchangeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.INTEGRAL
     *
     * @return the value of customer.INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.INTEGRAL
     *
     * @param integral the value for customer.INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MAIL_CHECKED
     *
     * @return the value of customer.MAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Boolean getMailChecked() {
        return mailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MAIL_CHECKED
     *
     * @param mailChecked the value for customer.MAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setMailChecked(Boolean mailChecked) {
        this.mailChecked = mailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MOBILE
     *
     * @return the value of customer.MOBILE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MOBILE
     *
     * @param mobile the value for customer.MOBILE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.MOBILE_CHECKED
     *
     * @return the value of customer.MOBILE_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Boolean getMobileChecked() {
        return mobileChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.MOBILE_CHECKED
     *
     * @param mobileChecked the value for customer.MOBILE_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setMobileChecked(Boolean mobileChecked) {
        this.mobileChecked = mobileChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PASSWORD
     *
     * @return the value of customer.PASSWORD
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PASSWORD
     *
     * @param password the value for customer.PASSWORD
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.POST_CODE
     *
     * @return the value of customer.POST_CODE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.POST_CODE
     *
     * @param postCode the value for customer.POST_CODE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PROVINCE
     *
     * @return the value of customer.PROVINCE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PROVINCE
     *
     * @param province the value for customer.PROVINCE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.QQ_ACCESS_TOKEN
     *
     * @return the value of customer.QQ_ACCESS_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getQqAccessToken() {
        return qqAccessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.QQ_ACCESS_TOKEN
     *
     * @param qqAccessToken the value for customer.QQ_ACCESS_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setQqAccessToken(String qqAccessToken) {
        this.qqAccessToken = qqAccessToken == null ? null : qqAccessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.QQ_FIGURE_URL
     *
     * @return the value of customer.QQ_FIGURE_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getQqFigureUrl() {
        return qqFigureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.QQ_FIGURE_URL
     *
     * @param qqFigureUrl the value for customer.QQ_FIGURE_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setQqFigureUrl(String qqFigureUrl) {
        this.qqFigureUrl = qqFigureUrl == null ? null : qqFigureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.QQ_NICK_NAME
     *
     * @return the value of customer.QQ_NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getQqNickName() {
        return qqNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.QQ_NICK_NAME
     *
     * @param qqNickName the value for customer.QQ_NICK_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setQqNickName(String qqNickName) {
        this.qqNickName = qqNickName == null ? null : qqNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.QQ_OPEN_ID
     *
     * @return the value of customer.QQ_OPEN_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getQqOpenId() {
        return qqOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.QQ_OPEN_ID
     *
     * @param qqOpenId the value for customer.QQ_OPEN_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setQqOpenId(String qqOpenId) {
        this.qqOpenId = qqOpenId == null ? null : qqOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.REAL_NAME
     *
     * @return the value of customer.REAL_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.REAL_NAME
     *
     * @param realName the value for customer.REAL_NAME
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.REMARK
     *
     * @return the value of customer.REMARK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.REMARK
     *
     * @param remark the value for customer.REMARK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.SEX
     *
     * @return the value of customer.SEX
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.SEX
     *
     * @param sex the value for customer.SEX
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.TELEPHONE
     *
     * @return the value of customer.TELEPHONE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.TELEPHONE
     *
     * @param telephone the value for customer.TELEPHONE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.TOTAL_INTEGRAL
     *
     * @return the value of customer.TOTAL_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getTotalIntegral() {
        return totalIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.TOTAL_INTEGRAL
     *
     * @param totalIntegral the value for customer.TOTAL_INTEGRAL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setTotalIntegral(Integer totalIntegral) {
        this.totalIntegral = totalIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RANK
     *
     * @return the value of customer.RANK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RANK
     *
     * @param rank the value for customer.RANK
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.EMAIL_CHECKED
     *
     * @return the value of customer.EMAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Boolean getEmailChecked() {
        return emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.EMAIL_CHECKED
     *
     * @param emailChecked the value for customer.EMAIL_CHECKED
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setEmailChecked(Boolean emailChecked) {
        this.emailChecked = emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RONG_CLOUD_TOKEN
     *
     * @return the value of customer.RONG_CLOUD_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getRongCloudToken() {
        return rongCloudToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RONG_CLOUD_TOKEN
     *
     * @param rongCloudToken the value for customer.RONG_CLOUD_TOKEN
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setRongCloudToken(String rongCloudToken) {
        this.rongCloudToken = rongCloudToken == null ? null : rongCloudToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.AVATAR_URL
     *
     * @return the value of customer.AVATAR_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.AVATAR_URL
     *
     * @param avatarUrl the value for customer.AVATAR_URL
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.RECOMMEND_CUSTOMER_ID
     *
     * @return the value of customer.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getRecommendCustomerId() {
        return recommendCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.RECOMMEND_CUSTOMER_ID
     *
     * @param recommendCustomerId the value for customer.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setRecommendCustomerId(Integer recommendCustomerId) {
        this.recommendCustomerId = recommendCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PRAISE
     *
     * @return the value of customer.PRAISE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PRAISE
     *
     * @param praise the value for customer.PRAISE
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.PRAISE_NUM
     *
     * @return the value of customer.PRAISE_NUM
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public Integer getPraiseNum() {
        return praiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.PRAISE_NUM
     *
     * @param praiseNum the value for customer.PRAISE_NUM
     *
     * @mbg.generated Sat Jul 21 15:53:32 CST 2018
     */
    public void setPraiseNum(Integer praiseNum) {
        this.praiseNum = praiseNum;
    }
}