package com.yunxin.cb.mall.entity;

/**
 * DeliveryAddress 数据实体类
 */
public class DeliveryAddress implements java.io.Serializable{


    private static final long serialVersionUID = 4771111259952152508L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.ADDRESS_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.ADDRESS_TYPE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private Integer addressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CITY
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CONSIGNEE_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String consigneeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CONSIGNEE_MOBILE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String consigneeMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CONSIGNEE_NAME
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String consigneeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CONSIGNEE_TELEPHONE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String consigneeTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.DEFAULT_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private Boolean defaultAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.DISTRICT
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.POST_CODE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.PROVINCE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.REMARK
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.CUSTOMER_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.ADDRESS_ID
     *
     * @return the value of delivery_address.ADDRESS_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.ADDRESS_ID
     *
     * @param addressId the value for delivery_address.ADDRESS_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.ADDRESS_TYPE
     *
     * @return the value of delivery_address.ADDRESS_TYPE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public Integer getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.ADDRESS_TYPE
     *
     * @param addressType the value for delivery_address.ADDRESS_TYPE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setAddressType(Integer addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CITY
     *
     * @return the value of delivery_address.CITY
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CITY
     *
     * @param city the value for delivery_address.CITY
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CONSIGNEE_ADDRESS
     *
     * @return the value of delivery_address.CONSIGNEE_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CONSIGNEE_ADDRESS
     *
     * @param consigneeAddress the value for delivery_address.CONSIGNEE_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CONSIGNEE_MOBILE
     *
     * @return the value of delivery_address.CONSIGNEE_MOBILE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getConsigneeMobile() {
        return consigneeMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CONSIGNEE_MOBILE
     *
     * @param consigneeMobile the value for delivery_address.CONSIGNEE_MOBILE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setConsigneeMobile(String consigneeMobile) {
        this.consigneeMobile = consigneeMobile == null ? null : consigneeMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CONSIGNEE_NAME
     *
     * @return the value of delivery_address.CONSIGNEE_NAME
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CONSIGNEE_NAME
     *
     * @param consigneeName the value for delivery_address.CONSIGNEE_NAME
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CONSIGNEE_TELEPHONE
     *
     * @return the value of delivery_address.CONSIGNEE_TELEPHONE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getConsigneeTelephone() {
        return consigneeTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CONSIGNEE_TELEPHONE
     *
     * @param consigneeTelephone the value for delivery_address.CONSIGNEE_TELEPHONE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setConsigneeTelephone(String consigneeTelephone) {
        this.consigneeTelephone = consigneeTelephone == null ? null : consigneeTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.DEFAULT_ADDRESS
     *
     * @return the value of delivery_address.DEFAULT_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public Boolean getDefaultAddress() {
        return defaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.DEFAULT_ADDRESS
     *
     * @param defaultAddress the value for delivery_address.DEFAULT_ADDRESS
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setDefaultAddress(Boolean defaultAddress) {
        this.defaultAddress = defaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.DISTRICT
     *
     * @return the value of delivery_address.DISTRICT
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.DISTRICT
     *
     * @param district the value for delivery_address.DISTRICT
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.POST_CODE
     *
     * @return the value of delivery_address.POST_CODE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.POST_CODE
     *
     * @param postCode the value for delivery_address.POST_CODE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.PROVINCE
     *
     * @return the value of delivery_address.PROVINCE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.PROVINCE
     *
     * @param province the value for delivery_address.PROVINCE
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.REMARK
     *
     * @return the value of delivery_address.REMARK
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.REMARK
     *
     * @param remark the value for delivery_address.REMARK
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.CUSTOMER_ID
     *
     * @return the value of delivery_address.CUSTOMER_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.CUSTOMER_ID
     *
     * @param customerId the value for delivery_address.CUSTOMER_ID
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}
