package com.yunxin.cb.mall.entity;

public class FloorCategory implements java.io.Serializable{
    private static final long serialVersionUID = -8039770727479012709L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_category.CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_category.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    private Integer floorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_category.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_category.CATEGORY_ID
     *
     * @return the value of floor_category.CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_category.CATEGORY_ID
     *
     * @param categoryId the value for floor_category.CATEGORY_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_category.FLOOR_ID
     *
     * @return the value of floor_category.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_category.FLOOR_ID
     *
     * @param floorId the value for floor_category.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_category.SORT_ORDER
     *
     * @return the value of floor_category.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_category.SORT_ORDER
     *
     * @param sortOrder the value for floor_category.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:23 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}