package com.yunxin.cb.mall.entity;

public class HomeFloor implements java.io.Serializable{
    private static final long serialVersionUID = -8686921924423185914L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer floorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.CATEGORY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer categoryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.COMMODITY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer commodityAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.ENABLED
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.FLOOR_LAYOUT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer floorLayout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.FLOOR_NAME
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private String floorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.ICON_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private String iconPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.IMAGE_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.REMARK
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_floor.BRAND_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    private Integer brandAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.FLOOR_ID
     *
     * @return the value of home_floor.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.FLOOR_ID
     *
     * @param floorId the value for home_floor.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.CATEGORY_AMOUNT
     *
     * @return the value of home_floor.CATEGORY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getCategoryAmount() {
        return categoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.CATEGORY_AMOUNT
     *
     * @param categoryAmount the value for home_floor.CATEGORY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setCategoryAmount(Integer categoryAmount) {
        this.categoryAmount = categoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.COMMODITY_AMOUNT
     *
     * @return the value of home_floor.COMMODITY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getCommodityAmount() {
        return commodityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.COMMODITY_AMOUNT
     *
     * @param commodityAmount the value for home_floor.COMMODITY_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setCommodityAmount(Integer commodityAmount) {
        this.commodityAmount = commodityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.ENABLED
     *
     * @return the value of home_floor.ENABLED
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.ENABLED
     *
     * @param enabled the value for home_floor.ENABLED
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.FLOOR_LAYOUT
     *
     * @return the value of home_floor.FLOOR_LAYOUT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getFloorLayout() {
        return floorLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.FLOOR_LAYOUT
     *
     * @param floorLayout the value for home_floor.FLOOR_LAYOUT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setFloorLayout(Integer floorLayout) {
        this.floorLayout = floorLayout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.FLOOR_NAME
     *
     * @return the value of home_floor.FLOOR_NAME
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public String getFloorName() {
        return floorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.FLOOR_NAME
     *
     * @param floorName the value for home_floor.FLOOR_NAME
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setFloorName(String floorName) {
        this.floorName = floorName == null ? null : floorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.ICON_PATH
     *
     * @return the value of home_floor.ICON_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.ICON_PATH
     *
     * @param iconPath the value for home_floor.ICON_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath == null ? null : iconPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.IMAGE_PATH
     *
     * @return the value of home_floor.IMAGE_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.IMAGE_PATH
     *
     * @param imagePath the value for home_floor.IMAGE_PATH
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.REMARK
     *
     * @return the value of home_floor.REMARK
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.REMARK
     *
     * @param remark the value for home_floor.REMARK
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.SORT_ORDER
     *
     * @return the value of home_floor.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.SORT_ORDER
     *
     * @param sortOrder the value for home_floor.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_floor.BRAND_AMOUNT
     *
     * @return the value of home_floor.BRAND_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public Integer getBrandAmount() {
        return brandAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_floor.BRAND_AMOUNT
     *
     * @param brandAmount the value for home_floor.BRAND_AMOUNT
     *
     * @mbg.generated Wed Jul 18 14:33:48 CST 2018
     */
    public void setBrandAmount(Integer brandAmount) {
        this.brandAmount = brandAmount;
    }
}