package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.Brand;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Wed Jul 18 14:35:20 CST 2018
     */
    @Delete({
        "delete from brand",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Wed Jul 18 14:35:20 CST 2018
     */
    @Insert({
        "insert into brand (BRAND_ID, BRAND_EN_NAME, ",
        "BRAND_KEY, BRAND_NAME, ",
        "BRAND_NO, BRAND_TITLE, ",
        "CREATE_TIME, DESCRIPTION, ",
        "DISPLAY, ENABLED, HOT, ",
        "PIC_PATH, REMARK, ",
        "SEO_DESCRIPTION, SEO_KEY, ",
        "SEO_TITLE, WEBSITE, ",
        "CATEGORY_ID)",
        "values (#{brandId,jdbcType=INTEGER}, #{brandEnName,jdbcType=VARCHAR}, ",
        "#{brandKey,jdbcType=VARCHAR}, #{brandName,jdbcType=VARCHAR}, ",
        "#{brandNo,jdbcType=VARCHAR}, #{brandTitle,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{description,jdbcType=VARCHAR}, ",
        "#{display,jdbcType=BIT}, #{enabled,jdbcType=BIT}, #{hot,jdbcType=BIT}, ",
        "#{picPath,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{seoDescription,jdbcType=VARCHAR}, #{seoKey,jdbcType=VARCHAR}, ",
        "#{seoTitle,jdbcType=VARCHAR}, #{website,jdbcType=VARCHAR}, ",
        "#{categoryId,jdbcType=INTEGER})"
    })
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Wed Jul 18 14:35:20 CST 2018
     */
    @Select({
        "select",
        "BRAND_ID, BRAND_EN_NAME, BRAND_KEY, BRAND_NAME, BRAND_NO, BRAND_TITLE, CREATE_TIME, ",
        "DESCRIPTION, DISPLAY, ENABLED, HOT, PIC_PATH, REMARK, SEO_DESCRIPTION, SEO_KEY, ",
        "SEO_TITLE, WEBSITE, CATEGORY_ID",
        "from brand",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}",
            "and enabled=1"
    })
    @Results({
        @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="BRAND_EN_NAME", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_KEY", property="brandKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_NAME", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_NO", property="brandNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_TITLE", property="brandTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="DISPLAY", property="display", jdbcType=JdbcType.BIT),
        @Result(column="ENABLED", property="enabled", jdbcType=JdbcType.BIT),
        @Result(column="HOT", property="hot", jdbcType=JdbcType.BIT),
        @Result(column="PIC_PATH", property="picPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_DESCRIPTION", property="seoDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_KEY", property="seoKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_TITLE", property="seoTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="WEBSITE", property="website", jdbcType=JdbcType.VARCHAR),
        @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER)
    })
    Brand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Wed Jul 18 14:35:20 CST 2018
     */
    @Select({
        "select",
        "BRAND_ID, BRAND_EN_NAME, BRAND_KEY, BRAND_NAME, BRAND_NO, BRAND_TITLE, CREATE_TIME, ",
        "DESCRIPTION, DISPLAY, ENABLED, HOT, PIC_PATH, REMARK, SEO_DESCRIPTION, SEO_KEY, ",
        "SEO_TITLE, WEBSITE, CATEGORY_ID",
        "from brand"
    })
    @Results({
        @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="BRAND_EN_NAME", property="brandEnName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_KEY", property="brandKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_NAME", property="brandName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_NO", property="brandNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRAND_TITLE", property="brandTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="DISPLAY", property="display", jdbcType=JdbcType.BIT),
        @Result(column="ENABLED", property="enabled", jdbcType=JdbcType.BIT),
        @Result(column="HOT", property="hot", jdbcType=JdbcType.BIT),
        @Result(column="PIC_PATH", property="picPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_DESCRIPTION", property="seoDescription", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_KEY", property="seoKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEO_TITLE", property="seoTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="WEBSITE", property="website", jdbcType=JdbcType.VARCHAR),
        @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER)
    })
    List<Brand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Wed Jul 18 14:35:20 CST 2018
     */
    @Update({
        "update brand",
        "set BRAND_EN_NAME = #{brandEnName,jdbcType=VARCHAR},",
          "BRAND_KEY = #{brandKey,jdbcType=VARCHAR},",
          "BRAND_NAME = #{brandName,jdbcType=VARCHAR},",
          "BRAND_NO = #{brandNo,jdbcType=VARCHAR},",
          "BRAND_TITLE = #{brandTitle,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "DESCRIPTION = #{description,jdbcType=VARCHAR},",
          "DISPLAY = #{display,jdbcType=BIT},",
          "ENABLED = #{enabled,jdbcType=BIT},",
          "HOT = #{hot,jdbcType=BIT},",
          "PIC_PATH = #{picPath,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "SEO_DESCRIPTION = #{seoDescription,jdbcType=VARCHAR},",
          "SEO_KEY = #{seoKey,jdbcType=VARCHAR},",
          "SEO_TITLE = #{seoTitle,jdbcType=VARCHAR},",
          "WEBSITE = #{website,jdbcType=VARCHAR},",
          "CATEGORY_ID = #{categoryId,jdbcType=INTEGER}",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Brand record);

    @Select({
            "select",
            "BRAND_ID, BRAND_EN_NAME, BRAND_KEY, BRAND_NAME, BRAND_NO, BRAND_TITLE, CREATE_TIME, ",
            "DESCRIPTION, DISPLAY, ENABLED, HOT, PIC_PATH, REMARK, SEO_DESCRIPTION, SEO_KEY, ",
            "SEO_TITLE, WEBSITE, CATEGORY_ID",
            "from brand",
            "where hot = 1"
    })
    @Results({
            @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="BRAND_EN_NAME", property="brandEnName", jdbcType=JdbcType.VARCHAR),
            @Result(column="BRAND_KEY", property="brandKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="BRAND_NAME", property="brandName", jdbcType=JdbcType.VARCHAR),
            @Result(column="BRAND_NO", property="brandNo", jdbcType=JdbcType.VARCHAR),
            @Result(column="BRAND_TITLE", property="brandTitle", jdbcType=JdbcType.VARCHAR),
            @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
            @Result(column="DISPLAY", property="display", jdbcType=JdbcType.BIT),
            @Result(column="ENABLED", property="enabled", jdbcType=JdbcType.BIT),
            @Result(column="HOT", property="hot", jdbcType=JdbcType.BIT),
            @Result(column="PIC_PATH", property="picPath", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="SEO_DESCRIPTION", property="seoDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="SEO_KEY", property="seoKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="SEO_TITLE", property="seoTitle", jdbcType=JdbcType.VARCHAR),
            @Result(column="WEBSITE", property="website", jdbcType=JdbcType.VARCHAR),
            @Result(column="CATEGORY_ID", property="categoryId", jdbcType=JdbcType.INTEGER)
    })
    List<Brand> selectHotBrand();
}