package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.DeliveryAddress;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface DeliveryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    @Delete({
            "delete from delivery_address",
            "where ADDRESS_ID = #{addressId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    @Insert({
            "insert into delivery_address (ADDRESS_ID, ADDRESS_TYPE, ",
            "CITY, CONSIGNEE_ADDRESS, ",
            "CONSIGNEE_MOBILE, CONSIGNEE_NAME, ",
            "CONSIGNEE_TELEPHONE, DEFAULT_ADDRESS, ",
            "DISTRICT, POST_CODE, ",
            "PROVINCE, REMARK, ",
            "CUSTOMER_ID)",
            "values (#{addressId,jdbcType=INTEGER}, #{addressType,jdbcType=INTEGER,typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler}, ",
            "#{city,jdbcType=VARCHAR}, #{consigneeAddress,jdbcType=VARCHAR}, ",
            "#{consigneeMobile,jdbcType=VARCHAR}, #{consigneeName,jdbcType=VARCHAR}, ",
            "#{consigneeTelephone,jdbcType=VARCHAR}, #{defaultAddress,jdbcType=BIT}, ",
            "#{district,jdbcType=VARCHAR}, #{postCode,jdbcType=VARCHAR}, ",
            "#{province,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
            "#{customerId,jdbcType=INTEGER})"
    })
    int insert(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    @Select({
            "select",
            "ADDRESS_ID, ADDRESS_TYPE, CITY, CONSIGNEE_ADDRESS, CONSIGNEE_MOBILE, CONSIGNEE_NAME, ",
            "CONSIGNEE_TELEPHONE, DEFAULT_ADDRESS, DISTRICT, POST_CODE, PROVINCE, REMARK, ",
            "CUSTOMER_ID",
            "from delivery_address",
            "where ADDRESS_ID = #{addressId,jdbcType=INTEGER}",
            "and CUSTOMER_ID = #{customerId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="ADDRESS_ID", property="addressId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="ADDRESS_TYPE", property="addressType",typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler.class),
            @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ADDRESS", property="consigneeAddress", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_MOBILE", property="consigneeMobile", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_NAME", property="consigneeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_TELEPHONE", property="consigneeTelephone", jdbcType=JdbcType.VARCHAR),
            @Result(column="DEFAULT_ADDRESS", property="defaultAddress", jdbcType=JdbcType.BIT),
            @Result(column="DISTRICT", property="district", jdbcType=JdbcType.VARCHAR),
            @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUSTOMER_ID", property="customerId", jdbcType=JdbcType.INTEGER)
    })
    DeliveryAddress selectByPrimaryKey(@Param("addressId") Integer addressId,@Param("customerId")Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    @Select({
            "select",
            "ADDRESS_ID, ADDRESS_TYPE, CITY, CONSIGNEE_ADDRESS, CONSIGNEE_MOBILE, CONSIGNEE_NAME, ",
            "CONSIGNEE_TELEPHONE, DEFAULT_ADDRESS, DISTRICT, POST_CODE, PROVINCE, REMARK, ",
            "CUSTOMER_ID",
            "from delivery_address"
    })
    @Results({
            @Result(column="ADDRESS_ID", property="addressId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="ADDRESS_TYPE", property="addressType", typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler.class),
            @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ADDRESS", property="consigneeAddress", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_MOBILE", property="consigneeMobile", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_NAME", property="consigneeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_TELEPHONE", property="consigneeTelephone", jdbcType=JdbcType.VARCHAR),
            @Result(column="DEFAULT_ADDRESS", property="defaultAddress", jdbcType=JdbcType.BIT),
            @Result(column="DISTRICT", property="district", jdbcType=JdbcType.VARCHAR),
            @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUSTOMER_ID", property="customerId", jdbcType=JdbcType.INTEGER)
    })
    List<DeliveryAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbg.generated Wed Jul 18 09:54:14 CST 2018
     */
    @Update({
            "update delivery_address",
            "set ADDRESS_TYPE = #{addressType,jdbcType=INTEGER,typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler},",
            "CITY = #{city,jdbcType=VARCHAR},",
            "CONSIGNEE_ADDRESS = #{consigneeAddress,jdbcType=VARCHAR},",
            "CONSIGNEE_MOBILE = #{consigneeMobile,jdbcType=VARCHAR},",
            "CONSIGNEE_NAME = #{consigneeName,jdbcType=VARCHAR},",
            "CONSIGNEE_TELEPHONE = #{consigneeTelephone,jdbcType=VARCHAR},",
            "DEFAULT_ADDRESS = #{defaultAddress,jdbcType=BIT},",
            "DISTRICT = #{district,jdbcType=VARCHAR},",
            "POST_CODE = #{postCode,jdbcType=VARCHAR},",
            "PROVINCE = #{province,jdbcType=VARCHAR},",
            "REMARK = #{remark,jdbcType=VARCHAR},",
            "CUSTOMER_ID = #{customerId,jdbcType=INTEGER}",
            "where ADDRESS_ID = #{addressId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DeliveryAddress record);

    /**
     * 根据用户ID查询收货地址列表
     */
    @Select({
            "select",
            "ADDRESS_ID, ADDRESS_TYPE, CITY, CONSIGNEE_ADDRESS, CONSIGNEE_MOBILE, CONSIGNEE_NAME, ",
            "CONSIGNEE_TELEPHONE, DEFAULT_ADDRESS, DISTRICT, POST_CODE, PROVINCE, REMARK, ",
            "CUSTOMER_ID",
            "from delivery_address",
            "where CUSTOMER_ID = #{customerId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="ADDRESS_ID", property="addressId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="ADDRESS_TYPE", property="addressType", typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler.class),
            @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ADDRESS", property="consigneeAddress", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_MOBILE", property="consigneeMobile", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_NAME", property="consigneeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_TELEPHONE", property="consigneeTelephone", jdbcType=JdbcType.VARCHAR),
            @Result(column="DEFAULT_ADDRESS", property="defaultAddress", jdbcType=JdbcType.BIT),
            @Result(column="DISTRICT", property="district", jdbcType=JdbcType.VARCHAR),
            @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUSTOMER_ID", property="customerId", jdbcType=JdbcType.INTEGER)
    })
    List<DeliveryAddress> selectByCustomerId(Integer customerId);

    /**
     * 查询用户默认收货地址
     */
    @Select({
            "select",
            "ADDRESS_ID, ADDRESS_TYPE, CITY, CONSIGNEE_ADDRESS, CONSIGNEE_MOBILE, CONSIGNEE_NAME, ",
            "CONSIGNEE_TELEPHONE, DEFAULT_ADDRESS, DISTRICT, POST_CODE, PROVINCE, REMARK, ",
            "CUSTOMER_ID",
            "from delivery_address",
            "where CUSTOMER_ID = #{customerId,jdbcType=INTEGER}",
            "and DEFAULT_ADDRESS = #{defaultAddress,jdbcType=BIT}"
    })
    @Results({
            @Result(column="ADDRESS_ID", property="addressId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="ADDRESS_TYPE", property="addressType", typeHandler=org.apache.ibatis.type.EnumOrdinalTypeHandler.class),
            @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_ADDRESS", property="consigneeAddress", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_MOBILE", property="consigneeMobile", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_NAME", property="consigneeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CONSIGNEE_TELEPHONE", property="consigneeTelephone", jdbcType=JdbcType.VARCHAR),
            @Result(column="DEFAULT_ADDRESS", property="defaultAddress", jdbcType=JdbcType.BIT),
            @Result(column="DISTRICT", property="district", jdbcType=JdbcType.VARCHAR),
            @Result(column="POST_CODE", property="postCode", jdbcType=JdbcType.VARCHAR),
            @Result(column="PROVINCE", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="CUSTOMER_ID", property="customerId", jdbcType=JdbcType.INTEGER)
    })
    DeliveryAddress selectDefaultByCustomerId(@Param("customerId")Integer customerId,@Param("defaultAddress")Boolean defaultAddress);
}
