package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.FloorBrand;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface FloorBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_brand
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    @Delete({
        "delete from floor_brand",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("brandId") Integer brandId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_brand
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    @Insert({
        "insert into floor_brand (BRAND_ID, FLOOR_ID, ",
        "SORT_ORDER)",
        "values (#{brandId,jdbcType=INTEGER}, #{floorId,jdbcType=INTEGER}, ",
        "#{sortOrder,jdbcType=INTEGER})"
    })
    int insert(FloorBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_brand
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    @Select({
        "select",
        "BRAND_ID, FLOOR_ID, SORT_ORDER",
        "from floor_brand",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    FloorBrand selectByPrimaryKey(@Param("brandId") Integer brandId, @Param("floorId") Integer floorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_brand
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    @Select({
        "select",
        "BRAND_ID, FLOOR_ID, SORT_ORDER",
        "from floor_brand"
    })
    @Results({
        @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorBrand> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table floor_brand
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    @Update({
        "update floor_brand",
        "set SORT_ORDER = #{sortOrder,jdbcType=INTEGER}",
        "where BRAND_ID = #{brandId,jdbcType=INTEGER}",
          "and FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(FloorBrand record);

    @Select({
            "select",
            "BRAND_ID, FLOOR_ID, SORT_ORDER",
            "from floor_brand",
            "where FLOOR_ID = #{floorId,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="BRAND_ID", property="brandId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="FLOOR_ID", property="floorId", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="SORT_ORDER", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<FloorBrand> selectByFloorId(Integer floorId);
}