package com.yunxin.cb.mall.mapper;

import com.yunxin.cb.mall.entity.OrderLoanApply;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface OrderLoanApplyMapper {
    final static String columns = "LOAN_ID, LOAN_CODE, CUSTOMER_ID, ORDER_ID, LOAN_STATE, LOAN_PRICE, AUDIT_REMARK, " +
            "AUDIT_STATE, CREATE_TIME, UPDATE_TIME, REMARK";
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_loan_apply
     *
     * @mbg.generated Sat Jul 21 10:42:45 CST 2018
     */
    @Delete({
        "delete from order_loan_apply",
        "where LOAN_ID = #{loanId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer loanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_loan_apply
     *
     * @mbg.generated Sat Jul 21 10:42:45 CST 2018
     */
    @Insert({
        "insert into order_loan_apply (",
            columns,
        ")",
        "values (#{loanId,jdbcType=INTEGER}, #{loanCode,jdbcType=VARCHAR}, ",
        "#{customerId,jdbcType=INTEGER}, #{orderId,jdbcType=INTEGER}, ",
        "#{loanState,jdbcType=INTEGER}, #{loanPrice,jdbcType=DOUBLE}, ",
        "#{auditRemark,jdbcType=VARCHAR}, #{auditState,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(OrderLoanApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_loan_apply
     *
     * @mbg.generated Sat Jul 21 10:42:45 CST 2018
     */
    @Select({
        "select",
            columns,
        "from order_loan_apply",
        "where LOAN_ID = #{loanId,jdbcType=INTEGER}"
    })
    @Results(id = "orderLoanApplyMap", value = {
        @Result(column="LOAN_ID", property="loanId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="LOAN_CODE", property="loanCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUSTOMER_ID", property="customerId", jdbcType=JdbcType.INTEGER),
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="LOAN_STATE", property="loanState", jdbcType=JdbcType.INTEGER),
        @Result(column="LOAN_PRICE", property="loanPrice", jdbcType=JdbcType.DOUBLE),
        @Result(column="AUDIT_REMARK", property="auditRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUDIT_STATE", property="auditState", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UPDATE_TIME", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    OrderLoanApply selectByPrimaryKey(Integer loanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_loan_apply
     *
     * @mbg.generated Sat Jul 21 10:42:45 CST 2018
     */
    @Select({
        "select",
            columns,
        "from order_loan_apply"
    })
    @ResultMap(value="orderLoanApplyMap")
    List<OrderLoanApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_loan_apply
     *
     * @mbg.generated Sat Jul 21 10:42:45 CST 2018
     */
    @Update({
        "update order_loan_apply",
        "set LOAN_CODE = #{loanCode,jdbcType=VARCHAR},",
          "CUSTOMER_ID = #{customerId,jdbcType=INTEGER},",
          "ORDER_ID = #{orderId,jdbcType=INTEGER},",
          "LOAN_STATE = #{loanState,jdbcType=INTEGER},",
          "LOAN_PRICE = #{loanPrice,jdbcType=DOUBLE},",
          "AUDIT_REMARK = #{auditRemark,jdbcType=VARCHAR},",
          "AUDIT_STATE = #{auditState,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP},",
          "REMARK = #{remark,jdbcType=VARCHAR}",
        "where LOAN_ID = #{loanId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderLoanApply record);

    @Select({
            "select",
            columns,
            "from order_loan_apply",
            "where ORDER_ID = #{orderId,jdbcType=INTEGER}",
            "limit 1"
    })
    @ResultMap(value="orderLoanApplyMap")
    OrderLoanApply selectByOrderId(@Param("orderId") Integer orderId);
}