# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://119.23.59.102:3306/crystal_ball?useUnicode=true&autoReconnect=true
    username: root
    password: Yunxin1234
  session:
     store-type: none
  redis:
     database: 0
     host: localhost
     port: 6379
     password:
     timeout: 0
     pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
  jpa:
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: com.yunxin.core.orm.ImprovedPhysicalNamingStrategy
      show-sql: true
      open-in-view: false
      properties:
          hibernate.format_sql: true
          hibernate.search.default.indexBase: /opt/www/cb/api/index
#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball
  domain-1: http://test.resource.999shuijingqiu.com/

#融云IM
rongcloud:
  appKey: z3v5yqkbz1jp0
  appSecret: AUUwTO6vXg7y7P

#APP自定义配置
application:
  default:
    avatarUrl: http://test.resource.999shuijingqiu.com/avatar.png
