# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skc?useUnicode=true&autoReconnect=true
    username: root
    password: Yunxin@2018!#%
  session:
     store-type: none
  jpa:
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: com.yunxin.core.orm.ImprovedPhysicalNamingStrategy
      show-sql: false
      open-in-view: false
      properties:
          hibernate.format_sql: false
          hibernate.search.default.indexBase: /data/webapps/api/temp/index
#7牛云存储
qiniu:
  accessKey: ewsiGNq3V0B5p3XSZQkI9UndbxQDD03q5WiL-63k
  secretKey: 9fglZdOXWmLXbU1rzroDOr2anFZydhnuKZjzBb-c
  bucket-1: crystal-ball-prod
  bucket-2: crystal-ball-paperwork-prod
  domain-1: http://resource.999shuijingqiu.com/
  domain-2: http://pc73xwx6z.bkt.clouddn.com/

#融云IM
rongcloud:
  appKey: vnroth0kv8sxo
  appSecret: xR4RmfFyJhA

#APP自定义配置
application:
  default:
    avatarUrl: http://resource.999shuijingqiu.com/avatar.png
