# 开发环境配置
spring:
  datasource:
     url: jdbc:mysql://192.168.0.104:3306/crystal_ball?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
     username: root
     password: 123456
  session:
     store-type: none
  jpa:
      hibernate:
          ddl-auto: none
          naming:
              physical-strategy: com.yunxin.core.orm.ImprovedPhysicalNamingStrategy
      show-sql: true
      open-in-view: false
      properties:
          hibernate.format_sql: true


security:
  basic:
    enabled: false