package com.yunxin.cb.console.entity;

// Generated 2010-8-3 16:46:33 by Hibernate Tools 3.2.4.GA

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.yunxin.cb.security.Privilege;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TblBaseSystemUser generated by hbm2java
 * 在此标记不生成json对象的属性，这里我标记了两个属性一个hibernateLazyInitializer属性
 */
@JsonAutoDetect
@Entity
@Table(name = "role_resc")
@DynamicInsert
@DynamicUpdate
public class RoleResc implements java.io.Serializable, Privilege {

    private static final long serialVersionUID = 1L;

    private int rescId;
    private Role role;

    /**
     * 资源编码
     */
    private String rescCode;

    public RoleResc() {
    }

    public RoleResc(int userId) {
        this.rescId = userId;
    }


    public RoleResc(Role role, String rescCode) {
        super();
        this.role = role;
        this.rescCode = rescCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(unique = true, nullable = false, precision = 12, scale = 0)
    public int getRescId() {
        return this.rescId;
    }

    public void setRescId(int userId) {
        this.rescId = userId;
    }

    @ManyToOne(fetch = FetchType.EAGER, optional = true)
    @JoinColumn(name = "ROLE_ID", nullable = false)
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role concent) {
        this.role = concent;
    }

    @Column(length = 64)
    public String getRescCode() {
        return this.rescCode;
    }

    public void setRescCode(String userName) {
        this.rescCode = userName;
    }

    @Override
    @Transient
    public String getResourceCode() {
        return this.rescCode;
    }

    @Override
    @Transient
    public String getRoleCode() {
        return role.getRoleName();
    }
}
