package com.yunxin.cb.mall.entity;

// Generated 2010-4-1 12:26:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicCollectionId generated by hbm2java
 */
@Embeddable
public class CommoditySpecId implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int commodityId;
    private int specId;

    public CommoditySpecId() {
    }

    public CommoditySpecId(int commodityId, int specId) {
        this.commodityId = commodityId;
        this.specId = specId;
    }

    @Column(nullable = false)
    public int getCommodityId() {
        return this.commodityId;
    }

    public void setCommodityId(int userId) {
        this.commodityId = userId;
    }

    @Column(nullable = false)
    public int getSpecId() {
        return this.specId;
    }

    public void setSpecId(int musicId) {
        this.specId = musicId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        CommoditySpecId that = (CommoditySpecId) o;

        if (commodityId != that.commodityId) return false;
        return specId == that.specId;

    }

    @Override
    public int hashCode() {
        int result = commodityId;
        result = 31 * result + specId;
        return result;
    }
}
