package com.yunxin.cb.mall.entity;

// Generated 2010-4-1 12:26:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicCollectionId generated by hbm2java
 */
@Embeddable
public class FloorCategoryId implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int floorId;
    private int categoryId;

    public FloorCategoryId() {
    }

    public FloorCategoryId(int floorId, int categoryId) {
        this.floorId = floorId;
        this.categoryId = categoryId;
    }

    @Column(nullable = false)
    public int getFloorId() {
        return this.floorId;
    }

    public void setFloorId(int userId) {
        this.floorId = userId;
    }

    @Column(nullable = false)
    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int musicId) {
        this.categoryId = musicId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FloorCategoryId that = (FloorCategoryId) o;

        if (floorId != that.floorId) return false;
        return categoryId == that.categoryId;

    }

    @Override
    public int hashCode() {
        int result = floorId;
        result = 31 * result + categoryId;
        return result;
    }
}
