package com.yunxin.cb.mall.entity;

// Generated 2010-4-1 12:26:41 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MusicCollectionId generated by hbm2java
 */
@Embeddable
public class FloorCommodityId implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int commodityId;
    private int floorId;

    public FloorCommodityId() {
    }

    public FloorCommodityId(int floorId, int commodityId) {
        this.commodityId = commodityId;
        this.floorId = floorId;
    }

    @Column(nullable = false)
    public int getCommodityId() {
        return this.commodityId;
    }

    public void setCommodityId(int userId) {
        this.commodityId = userId;
    }

    @Column(nullable = false)
    public int getFloorId() {
        return this.floorId;
    }

    public void setFloorId(int musicId) {
        this.floorId = musicId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FloorCommodityId that = (FloorCommodityId) o;

        if (commodityId != that.commodityId) return false;
        return floorId == that.floorId;

    }

    @Override
    public int hashCode() {
        int result = commodityId;
        result = 31 * result + floorId;
        return result;
    }
}
