package com.yunxin.cb.mall.entity;

import com.yunxin.cb.mall.entity.meta.AdvertisementPlace;
import com.yunxin.cb.mall.entity.meta.AdvertisementType;

import java.util.Date;

/**
 * 广告
 */
public class Advertisement implements java.io.Serializable{
    private static final long serialVersionUID = -5752835732783765235L;
    /**
     *
     */
    private Integer advertId;

    /**
     * 广告编码，用于前台网页的标记
     */
    private String advertCode;

    /**
     * 标题
     */
    private String advertTitle;

    /**
     * 广告URL
     */
    private String advertUrl;

    /**
     * 广告位
     */
    private AdvertisementPlace advertisementPlace;

    /**
     * 广告类型
     */
    private AdvertisementType advertisementType;

    /**
     * 广告URL类型
     */
    private Integer advertisementUrltype;

    /**
     * 客户端类型
     */
    private String clientTypes;

    /**
     * 内容
     */
    private String content;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 状态：true 启用；false 停用
     */
    private Boolean enabled;

    /**
     * 广告图片路径
     */
    private String picPath;

    /**
     * 备注
     */
    private String remark;

    /**
     * 备注
     */
    private String templatePath;

    /**
     * 视频路径
     */
    private String videoPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERT_ID
     *
     * @return the value of advertisement.ADVERT_ID
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public Integer getAdvertId() {
        return advertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERT_ID
     *
     * @param advertId the value for advertisement.ADVERT_ID
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertId(Integer advertId) {
        this.advertId = advertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERT_CODE
     *
     * @return the value of advertisement.ADVERT_CODE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getAdvertCode() {
        return advertCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERT_CODE
     *
     * @param advertCode the value for advertisement.ADVERT_CODE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertCode(String advertCode) {
        this.advertCode = advertCode == null ? null : advertCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERT_TITLE
     *
     * @return the value of advertisement.ADVERT_TITLE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getAdvertTitle() {
        return advertTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERT_TITLE
     *
     * @param advertTitle the value for advertisement.ADVERT_TITLE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertTitle(String advertTitle) {
        this.advertTitle = advertTitle == null ? null : advertTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERT_URL
     *
     * @return the value of advertisement.ADVERT_URL
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getAdvertUrl() {
        return advertUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERT_URL
     *
     * @param advertUrl the value for advertisement.ADVERT_URL
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertUrl(String advertUrl) {
        this.advertUrl = advertUrl == null ? null : advertUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERTISEMENT_PLACE
     *
     * @return the value of advertisement.ADVERTISEMENT_PLACE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public AdvertisementPlace getAdvertisementPlace() {
        return advertisementPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERTISEMENT_PLACE
     *
     * @param advertisementPlace the value for advertisement.ADVERTISEMENT_PLACE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertisementPlace(AdvertisementPlace advertisementPlace) {
        this.advertisementPlace = advertisementPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERTISEMENT_TYPE
     *
     * @return the value of advertisement.ADVERTISEMENT_TYPE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public AdvertisementType getAdvertisementType() {
        return advertisementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERTISEMENT_TYPE
     *
     * @param advertisementType the value for advertisement.ADVERTISEMENT_TYPE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertisementType(AdvertisementType advertisementType) {
        this.advertisementType = advertisementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ADVERTISEMENT_URLTYPE
     *
     * @return the value of advertisement.ADVERTISEMENT_URLTYPE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public Integer getAdvertisementUrltype() {
        return advertisementUrltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ADVERTISEMENT_URLTYPE
     *
     * @param advertisementUrltype the value for advertisement.ADVERTISEMENT_URLTYPE
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setAdvertisementUrltype(Integer advertisementUrltype) {
        this.advertisementUrltype = advertisementUrltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CLIENT_TYPES
     *
     * @return the value of advertisement.CLIENT_TYPES
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getClientTypes() {
        return clientTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CLIENT_TYPES
     *
     * @param clientTypes the value for advertisement.CLIENT_TYPES
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setClientTypes(String clientTypes) {
        this.clientTypes = clientTypes == null ? null : clientTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CONTENT
     *
     * @return the value of advertisement.CONTENT
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CONTENT
     *
     * @param content the value for advertisement.CONTENT
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.CREATE_TIME
     *
     * @return the value of advertisement.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.CREATE_TIME
     *
     * @param createTime the value for advertisement.CREATE_TIME
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ENABLED
     *
     * @return the value of advertisement.ENABLED
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ENABLED
     *
     * @param enabled the value for advertisement.ENABLED
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.PIC_PATH
     *
     * @return the value of advertisement.PIC_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.PIC_PATH
     *
     * @param picPath the value for advertisement.PIC_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.REMARK
     *
     * @return the value of advertisement.REMARK
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.REMARK
     *
     * @param remark the value for advertisement.REMARK
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.TEMPLATE_PATH
     *
     * @return the value of advertisement.TEMPLATE_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.TEMPLATE_PATH
     *
     * @param templatePath the value for advertisement.TEMPLATE_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath == null ? null : templatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.VIDEO_PATH
     *
     * @return the value of advertisement.VIDEO_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public String getVideoPath() {
        return videoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.VIDEO_PATH
     *
     * @param videoPath the value for advertisement.VIDEO_PATH
     *
     * @mbg.generated Wed Jul 18 10:38:52 CST 2018
     */
    public void setVideoPath(String videoPath) {
        this.videoPath = videoPath == null ? null : videoPath.trim();
    }
}