package com.yunxin.cb.mall.entity;

public class FloorBrand implements java.io.Serializable{
    private static final long serialVersionUID = -8623785684836614288L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_brand.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_brand.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    private Integer floorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_brand.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_brand.BRAND_ID
     *
     * @return the value of floor_brand.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_brand.BRAND_ID
     *
     * @param brandId the value for floor_brand.BRAND_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_brand.FLOOR_ID
     *
     * @return the value of floor_brand.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_brand.FLOOR_ID
     *
     * @param floorId the value for floor_brand.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_brand.SORT_ORDER
     *
     * @return the value of floor_brand.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_brand.SORT_ORDER
     *
     * @param sortOrder the value for floor_brand.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:27 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}