package com.yunxin.cb.mall.entity;

public class FloorCommodity implements java.io.Serializable{
    private static final long serialVersionUID = 2614464144545072813L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    private Integer commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_commodity.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    private Integer floorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column floor_commodity.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_commodity.COMMODITY_ID
     *
     * @return the value of floor_commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_commodity.COMMODITY_ID
     *
     * @param commodityId the value for floor_commodity.COMMODITY_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_commodity.FLOOR_ID
     *
     * @return the value of floor_commodity.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public Integer getFloorId() {
        return floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_commodity.FLOOR_ID
     *
     * @param floorId the value for floor_commodity.FLOOR_ID
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column floor_commodity.SORT_ORDER
     *
     * @return the value of floor_commodity.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column floor_commodity.SORT_ORDER
     *
     * @param sortOrder the value for floor_commodity.SORT_ORDER
     *
     * @mbg.generated Wed Jul 18 14:32:56 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}